version: 0.0
Resources:
  - TargetService:
      Type: AWS::EKS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancer:
          ContainerName: "claims-api"
          ContainerPort: 5000
Hooks:
  - BeforeInstall:
      - location: scripts/install_dependencies.ps1
        timeout: 300
        runas: root
  - ApplicationStart:
      - location: scripts/start_server.ps1
        timeout: 300
        runas: root
  - ApplicationStop:
      - location: scripts/stop_server.ps1
        timeout: 300
        runas: root