apiVersion: v1
kind: ServiceAccount
metadata:
  name: claims-api-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::621262609834:role/ClaimsAPI-EKS-ServiceRole-claims-api-service-role