apiVersion: v1
kind: Service
metadata:
  name: claims-api-service
  namespace: default
spec:
  selector:
    app: claims-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer